### ISSUE TITLE
API issue running plot_historic_sentiments.py

### ISSUE THREAD

**Issue by arnaudcisse44** [cryptomood/api#1]
Hi, I have tried to run the plot_historic_sentiments.py in python but I got the error message below, do you know what went wrong ? (Please do not assume anything as for my programming skills, I am a beginner).

```
runcell(0, '/Users/arnaudcisse/Documents/bitcoinProg/plot_historic_sentiments.py')
Traceback (most recent call last):

  File "/Users/arnaudcisse/Documents/bitcoinProg/plot_historic_sentiments.py", line 118, in <module>
    main()

  File "/Users/arnaudcisse/Documents/bitcoinProg/plot_historic_sentiments.py", line 113, in main
    candles_wrapper = get_historic_socials_sentiment(channel=channel, requests=requests)

  File "/Users/arnaudcisse/Documents/bitcoinProg/plot_historic_sentiments.py", line 74, in get_historic_socials_sentiment
    for candle in candle_stream:

  File "/opt/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()

  File "/opt/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 706, in _next
    raise self

_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed"
	debug_error_string = "{"created":"@1592179915.372044000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3962,"referenced_errors":[{"created":"@1592179915.372039000","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":214,"referenced_errors":[{"created":"@1592179915.372038000","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":369,"grpc_status":14,"referenced_errors":[{"created":"@1592179915.371978000","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":254,"referenced_errors":[{"created":"@1592179915.371964000","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":254}]}]}]}]}"
>
```

**Comment by cryptomood** [comment]
Hello.

Have you changed the variable on line 14 & 15? 
Right now it should be 'apiv1.cryptomood.com:443', path to certificate file, which can be downloaded from [here](https://docs.cryptomood.com/cryptomood.pem)

Since the public api is using token authorization, you should also have an account [here](https://cryptomood.com/sign-in/) and copy the token provided on your account page to line 85 (+uncomment line 85,86 for token authorization).

I believe we should prepare better readme as this is not 100% intuitive :)

**Comment by arnaudcisse44** [comment]
Good spot for the server address line (line 14) ! It works now, thanks a lot !
We can close the issue
